### ISSUE TITLE
verdubbeling totale waarde door sb.toString() 

### ISSUE THREAD

**Issue by Fuel4Death** [MaesD/Blackjack#2]
![screenshot_415](https://cloud.githubusercontent.com/assets/22810244/19762359/fa217556-9c39-11e6-9107-d2bb2e1bafca.png)

Bij het berekenen van de totale waarde van de hand van de dealer wordt deze blijkbaar verdubbeld.
Het probleem zit vermoedelijk in de methode `dealeraction()`

**Comment by MaesD** [comment]
bij debuggen geeft totalvalue de correcte waarde.
vb)
![totalvalue](http://image.prntscr.com/image/f36d7cddeb924179b1e5e5f8836dda9b.png)

geeft dit als resultaat:
![consoleprint](http://image.prntscr.com/image/f714116d60c5411aad5fd190d3a44f77.png)

M.a.w probleem zit in `dealer.toString()` methode.

Bij verder debuggen opgemerkt dat hij `totalvalue` verdubbeld bij `sb.toString()`

**Comment by Fuel4Death** [comment]
Probleem opgelost.
De totale waarde word nu in HandBLL berekent waardoor er in Hand enkel getters en setters overblijven

Eveneens heb ik ervoor gezorgd dat telkens wanneer `getTotalValue(Hand hand)` opgeroepen, de totale waarde initieel op 0 wordt geplaatst:
`int totalValue = 0;`
